In [1]:
# Import pandas, numpy, matplotlib, seaborn libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages
import datetime

In [2]:
dfweather = pd.read_csv('Custom_location_53_345035_-6_267261_62b5c8e6c91d98000ba01ceb.csv')

In [3]:
dfweather = dfweather[dfweather['dt_iso']>='2018-01-01'][dfweather['dt_iso']<='2018-12-31']

<ipython-input-3-85f09da4c9f6>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dfweather = dfweather[dfweather['dt_iso']>='2018-01-01'][dfweather['dt_iso']<='2018-12-31']

In [4]:
dfweather.head(20)

,dt,dt_iso,timezone,city_name,lat,lon,temp,visibility,dew_point,feels_like,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
9014,1514764800,2018-01-01 00:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,4.39,9999.0,2.26,-1.93,...,18.0,NaN,NaN,NaN,NaN,40,520,Rain,light intensity shower rain,09n
9015,1514768400,2018-01-01 01:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,4.39,9999.0,2.26,-1.68,...,NaN,NaN,NaN,NaN,NaN,75,520,Rain,light intensity shower rain,09n
9016,1514772000,2018-01-01 02:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.40,-0.47,...,18.5,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03n
9017,1514775600,2018-01-01 03:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.40,-0.47,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03n
9018,1514779200,2018-01-01 04:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.40,-0.33,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03n
9019,1514782800,2018-01-01 05:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.22,0.29,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
9020,1514786400,2018-01-01 06:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.00,9999.0,2.36,0.44,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
9021,1514790000,2018-01-01 07:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,4.46,9999.0,2.33,0.34,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
9022,1514793600,2018-01-01 08:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,4.39,9999.0,2.26,-0.16,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
9023,1514797200,2018-01-01 09:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,4.39,9999.0,2.26,-0.52,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
9024,1514800800,2018-01-01 10:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.40,0.16,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
9025,1514804400,2018-01-01 11:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,6.39,9999.0,3.37,0.88,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
9026,1514808000,2018-01-01 12:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,7.39,9999.0,3.44,2.23,...,17.5,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
9027,1514811600,2018-01-01 13:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,7.39,7000.0,4.35,2.13,...,19.0,NaN,NaN,NaN,NaN,75,520,Rain,light intensity shower rain,09d
9028,1514815200,2018-01-01 14:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,6.39,9999.0,3.37,0.88,...,17.5,NaN,NaN,NaN,NaN,40,520,Rain,light intensity shower rain,09d
9029,1514818800,2018-01-01 15:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,6.39,9999.0,4.22,1.01,...,NaN,NaN,NaN,NaN,NaN,75,520,Rain,light intensity shower rain,09d
9030,1514822400,2018-01-01 16:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,6.39,9999.0,3.37,1.24,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03d
9031,1514826000,2018-01-01 17:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,2.22,0.29,...,14.4,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02n
9032,1514829600,2018-01-01 18:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,3.24,1.12,...,NaN,NaN,NaN,NaN,NaN,20,801,Clouds,few clouds,02n
9033,1514833200,2018-01-01 19:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,5.39,9999.0,3.24,0.62,...,NaN,NaN,NaN,NaN,NaN,40,802,Clouds,scattered clouds,03n

In [5]:
dfweather.tail(20)

,dt,dt_iso,timezone,city_name,lat,lon,temp,visibility,dew_point,feels_like,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
18030,1546142400,2018-12-30 04:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.40,9999.0,9.82,10.95,...,6.26,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18031,1546146000,2018-12-30 05:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.40,9999.0,9.65,10.92,...,4.47,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18032,1546149600,2018-12-30 06:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.21,9999.0,9.13,10.66,...,5.36,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18033,1546153200,2018-12-30 07:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.04,9999.0,9.13,10.50,...,4.47,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18034,1546156800,2018-12-30 08:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.62,9999.0,8.38,9.98,...,2.24,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18035,1546160400,2018-12-30 09:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.62,9999.0,8.55,10.01,...,3.58,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18036,1546164000,2018-12-30 10:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.84,9999.0,8.42,10.20,...,3.58,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18037,1546167600,2018-12-30 11:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.52,9999.0,8.74,10.89,...,4.47,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18038,1546171200,2018-12-30 12:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.47,9999.0,8.33,10.79,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18039,1546174800,2018-12-30 13:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.51,9999.0,8.37,10.83,...,NaN,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18040,1546178400,2018-12-30 14:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.69,9999.0,8.17,10.98,...,2.68,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18041,1546182000,2018-12-30 15:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,11.42,9999.0,7.72,10.65,...,2.68,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18042,1546185600,2018-12-30 16:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.58,9999.0,7.46,9.81,...,3.58,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04d
18043,1546189200,2018-12-30 17:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.52,9999.0,7.93,9.82,...,3.13,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18044,1546192800,2018-12-30 18:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.53,9999.0,8.12,9.86,...,3.58,NaN,NaN,NaN,NaN,75,300,Drizzle,light intensity drizzle,09n
18045,1546196400,2018-12-30 19:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.36,9999.0,8.12,9.70,...,2.68,NaN,NaN,NaN,NaN,75,300,Drizzle,light intensity drizzle,09n
18046,1546200000,2018-12-30 20:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.36,9999.0,8.29,9.72,...,2.24,NaN,NaN,NaN,NaN,75,300,Drizzle,light intensity drizzle,09n
18047,1546203600,2018-12-30 21:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.53,9999.0,7.59,9.78,...,2.24,NaN,NaN,NaN,NaN,75,300,Drizzle,light intensity drizzle,09n
18048,1546207200,2018-12-30 22:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,10.36,9999.0,7.78,9.64,...,1.79,NaN,NaN,NaN,NaN,75,803,Clouds,broken clouds,04n
18049,1546210800,2018-12-30 23:00:00 +0000 UTC,0,Custom location,53.345035,-6.267261,9.69,9999.0,8.45,9.69,...,2.24,NaN,NaN,NaN,NaN,75,300,Drizzle,light intensity drizzle,09n

In [6]:
# saving the weather data of year 2018 to a local csv
dfweather.to_csv("weatherdata2018.csv", index=False)